wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/groundtruth/clipart.zip
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/infograph.zip
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/groundtruth/painting.zip
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/quickdraw.zip
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/real.zip
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/sketch.zip
unzip 'data/*.zip' -d data/
rm data/*.zip
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/clipart_train.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/clipart_test.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/infograph_train.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/infograph_test.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/painting_train.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/painting_test.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/quickdraw_train.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/quickdraw_test.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/real_train.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/real_test.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/sketch_train.txt
wget -P data/ http://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/sketch_test.txt
python generate_splits.py --dataset clipart
python generate_splits.py --dataset infograph
python generate_splits.py --dataset painting
python generate_splits.py --dataset quickdraw
python generate_splits.py --dataset real
python generate_splits.py --dataset sketch